name: OtomatikPiston
version: 1.0
author: Kekn9ne
main: com.kekn9ne.otomatikpiston.OtomatikPiston
api-version: 1.16

commands:
  otopiston:
    description: Main command of OtomatikPiston.
    aliases: [otomatikpiston]